version: '3.7'
services:
    web:
        image: "nginx:latest"
        command: [nginx-debug, '-g', 'daemon off;']
        ports:
            - "5000:80"
        volumes:
            - ./etc/nginx/conf.d/cartostory.conf:/etc/nginx/conf.d/default.conf
    client:
        image: cartostory-frontend:latest
        ports:
            - "8080:8080"
        build:
            context: .
            dockerfile: Dockerfile.dev
        command: run serve
        volumes:
            - ./src:/opt/app/src
            - ./auth_config.json:/opt/app/auth_config.json
            - ./package.json:/opt/app/package.json
            - ./.eslintrc.js:/opt/app/.eslintrc.js
            - ./babel.config.js:/opt/app/babel.config.js
            - ./vue.config.js:/opt/app/vue.config.js
            - ./public:/opt/app/public
networks:
    default:
        name: cartostory-net
