version: '3.7'
services:
    web:
        image: "nginx:latest"
        ports:
            - "5000:80"
        volumes:
            - client-volume:/usr/share/nginx/cartostory
            - ./etc/nginx/conf.d/cartostory.conf:/etc/nginx/conf.d/default.conf
    client:
        entrypoint: tail -f /dev/null
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - client-volume:/opt/app

# volume has to be used in an empty folder in services definitions (web, client)
volumes:
    client-volume:
networks:
    default:
        name: cartostory-prod-net
