FROM node:12.19.0-alpine AS node_base

RUN apk add git

FROM node_base AS deps
RUN mkdir /opt/app
WORKDIR /opt/app
RUN chown -R node:node /opt/app
USER node
COPY package*.json ./
RUN npm ci

FROM node_base AS dev
RUN mkdir /opt/app
WORKDIR /opt/app
RUN chown -R node:node /opt/app
USER node
COPY --from=deps --chown=node:node /opt/app/node_modules /opt/app/node_modules
ENTRYPOINT ["npm"]
EXPOSE 8080

