// new mutations
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const UPDATE_BBOX_BEING_ADDED = 'UPDATE_BBOX_BEING_ADDED';
export const UPDATE_BOUNDING_BOX_CALLBACK = 'UPDATE_BOUNDING_BOX_CALLBACK';
export const UPDATE_ERRORS = 'UPDATE_ERRORS';
export const UPDATE_EDITABLE = 'UPDATE_EDITABLE';
export const UPDATE_FEATURE_BEING_ADDED = 'UPDATE_FEATURE_BEING_ADDED';
export const UPDATE_HIGHLIGHTED_BBOX = 'UPDATE_HIGHLIGHTED_BBOX';
export const UPDATE_HIGHLIGHTED_LAT_LNG = 'UPDATE_HIGHLIGHTED_LAT_LNG';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_MAP_CENTER = 'UPDATE_MAP_CENTER';
export const UPDATE_SHOULD_TEXT_SCROLL = 'UPDATE_SHOULD_TEXT_SCROLL';
export const UPDATE_STORY = 'UPDATE_STORY';
export const UPDATE_STORY_NAME = 'UPDATE_STORY_NAME';
export const UPDATE_STORY_TEXT = 'UPDATE_STORY_TEXT';
export const UPDATE_STORY_URL = 'UPDATE_STORY_URL';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const UPDATE_TRACK = 'UPDATE_TRACK';

export const RESET_HIGHLIGHTED_LINK = 'RESET_HIGHLIGHTED_LINK';
export const SET_BBOX = 'SET_BBOX';
export const SET_BBOX_HOVERED = 'SET_BBOX_HOVERED';
export const SET_FEATURES_URL = 'SET_FEATURES_URL';
export const SET_HIGHLIGHTED_FEATURE = 'SET_HIGHLIGHTED_FEATURE';
export const SET_SHOULD_SCROLL_TO_FEATURE = 'SET_SHOULD_SCROLL_TO_FEATURE';
export const SET_STORY_NAME = 'SET_STORY_NAME';
export const SET_STORY_URL = 'SET_STORY_URL';
export const SET_TRACK_URL = 'SET_TRACK_URL';

// story mutations
export const SET_STORY = 'SET_STORY';

// track mutations
export const SET_TRACK = 'SET_TRACK';
